services:
  postgres:
    container_name: CRM_db
    image: postgres:15

    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: salesflow_crm
      POSTGRES_PASSWORD: crm_secure_password

volumes:
  postgres_data:
